### ISSUE TITLE
[QA] Frontend Webtools (Auth, CRU User, View Member + Wallet)

### ISSUE THREAD

**Issue by anra54** [purwaren/moflip-webtools#94]

**Comment by drmwnarief28** [comment]
| Aspect Testing | Input | Expected Result | Actual Result | Status (P/F) | Description |
|---|---|---|---|---|---|
| AUTH |  |  |  |  |  |
| login | email : fadhlan@coreinitiative.id | login success, redir to dashboard | As Expected | P |  |
|  |  |  |  |  |  |
| USER |  |  |  |  |  |
| read user |  | show list of users that has created | As Expected | P | Pada list of users, ketika email panjang dapat terjadi overlaping teks dengan table column role |
| create user | email : darmawanarief71@gmail.com | user success created | As Expected | P |  |
|  | email : ayamkuah0@gmail.com | fail to create user because there is the same user | As Expected | P |  |
| update user |  | user attribute updated |  |  |  |
|  |  |  |  |  |  |
| MEMBER |  |  |  |  |  |
| view member | - | show list member | As Expected | P |  |
|  |  |  |  |  |  |
| WALLET |  |  |  |  |  |
| view wallet |  | Show list wallets |  |  | Pending |
|  |  |  |  |  | [26/11/21] Telah menampilkan sesuai dengan respon API |

**Comment by drmwnarief28** [comment]
![image](https://user-images.githubusercontent.com/54920443/143536372-866d30fb-b5e1-4912-9f05-98abb600ab98.png)

**Comment by drmwnarief28** [comment]
Untuk list wallet dan detail wallet

Response API
![image](https://user-images.githubusercontent.com/54920443/143567046-d1ac11fc-890f-4f31-98a5-9da7454192f7.png)

Webtools
![image](https://user-images.githubusercontent.com/54920443/143567107-555b9e78-90ed-4ab1-b366-2964d5ebd7c4.png)
